### ISSUE TITLE
Not working - no subtitles found

### ISSUE THREAD

**Issue by CyberMew** [Diaoul/subliminal#429]
I just re-installed and it was unable to find any subtitles. Which is weird because it worked last year when I installed it up till a few days ago and I reinstalled it. Is there a specific version among the plugins that will work fine without issues? Here are my versions:

pip list
babelfish (0.5.3)
beautifulsoup4 (4.3.2)
chardet (2.3.0)
Cheetah (2.4.4)
dogpile.cache (0.5.4)
dogpile.core (0.4.1)
enzyme (0.4.1)
guessit (0.10.1)
html5lib (1.0b3)
pbr (0.10.7)
pip (6.0.6)
pyOpenSSL (0.13)
pysrt (1.0.1)
python-dateutil (2.4.0)
pyxdg (0.25)
requests (2.5.1)
setuptools (12.0.4)
six (1.9.0)
stevedore (1.2.0)
subliminal (0.8.0.dev0)
yenc (0.4.0)

**Comment by omaralvarez** [comment]
Are you getting messages like these?

INFO: Listing subtitles for <Episode [u'A', 2013, 2x7]>
INFO: Found 0 subtitles total

I upgraded to 0.8, before it was working fine...

**Comment by CyberMew** [comment]
Yup, exactly that. I thought it was a problem with guessit, but I tried all versions until all the way down to 0.7.0 which then gave me an error.

**Comment by h3llrais3r** [comment]
I confirm that subliminal is only tested with guessit 0.7.1.
See https://github.com/Diaoul/subliminal/commit/5ffa344f1c30dc14c2b6290d330e585e6223e961
Future version are not tested and may not be compatible

**Comment by omaralvarez** [comment]
I have opened an issue in guessit, I think it has to do with full paths, if you use guessit on a file without path it works fine, on the other hand if you include the full path it does not guess well.

**Comment by omaralvarez** [comment]
I can confirm with guessit 0.7.1 everything is working fine, although I'll try to see if I can make it work with 0.10.1 since the minimum version allowed in flexget is 0.9.3, and it does not work either. Now I had to create an special virtual env only for subliminal, and do not think that it is an optimal solution.

**Comment by h3llrais3r** [comment]
Version 0.9.3 of guessit should also work.
I'm running it with this version (see https://github.com/Diaoul/subliminal/pull/405) and it works fine.

**Comment by omaralvarez** [comment]
For me 0.9.3 works, but when guessing the series names, instead it uses the folder name. Its a really weird problem that does not happen with 0.7.1. But as I said earlier, I think its a guessit issue since I can reproduce it only using guessit.

**Comment by omaralvarez** [comment]
Just a heads up, my problem is fixed in guessit 0.10.2.

**Comment by CyberMew** [comment]
Nope, using guessit 0.10.2 and it still can't find subs for Arrow, Agents of shield, The Flash, etc. Downgraded to 0.7.1 and it worked. (except for shield though)

**Comment by SeeDborg** [comment]
Same problem for me with 0.7.5 and 0.8.0.
Didn't test 0.7.1 but maybe I will.

For Agents of SHIELD it's searching but never finds anything.
For the Flash it's not even searching, as if there were no files.

I think the problem is with special characters ( and .

**Comment by CyberMew** [comment]
No issues with flash series. Suggest you try with 0.7.1 and report back your results! :)

**Comment by SeeDborg** [comment]
I tried 0.7.1 but it wouldn't launch (error message, it's on a Banana Pi, maybe it's related).

The Flash is in a directory named "The Flash (2014)", it is the same for you ?

**Comment by CyberMew** [comment]
Yea

**Comment by CyberMew** [comment]
Still no go for 0.10.3 for latest 0.8 dev build
