### ISSUE TITLE
can't get legendastv subtitles

### ISSUE THREAD

**Issue by evertonbob** [Diaoul/subliminal#709]
What am i doing wrong?
`
bobs-iMac:~ bob$ subliminal --debug --legendastv user pass download -f -v -l pt-BR -p legendastv The.Walking.Dead.S07E01.HDTV.x264-KILLERS`

This occurred with every single episode

[debug.txt](https://github.com/Diaoul/subliminal/files/559722/debug.txt)

Thanks.

```
INFO:subliminal.providers.legendastv:Downloading archive 580da91eac76b
DEBUG:subliminal.providers.legendastv:Identified rar archive
ERROR:subliminal.core:Unexpected error in provider 'legendastv', discarding it
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/subliminal/core.py", line 171, in download_subtitle
    self[subtitle.provider_name].download_subtitle(subtitle)
  File "/Library/Python/2.7/site-packages/subliminal/providers/legendastv.py", line 448, in download_subtitle
    subtitle.content = fix_line_ending(subtitle.archive.content.read(subtitle.name))
  File "/Library/Python/2.7/site-packages/rarfile.py", line 629, in read
    return f.read()
  File "/Library/Python/2.7/site-packages/rarfile.py", line 1364, in read
    raise BadRarFile("Failed the read enough data")
BadRarFile: Failed the read enough data
WARNING:subliminal.core:Provider 'legendastv' is discarded
WARNING:subliminal.core:Provider 'legendastv' is discarded
WARNING:subliminal.core:Provider 'legendastv' is discarded
WARNING:subliminal.core:Provider 'legendastv' is discarded
WARNING:subliminal.core:Provider 'legendastv' is discarded
WARNING:subliminal.core:Provider 'legendastv' is discarded
WARNING:subliminal.core:Provider 'legendastv' is discarded
WARNING:subliminal.core:Provider 'legendastv' is discarded
WARNING:subliminal.core:Provider 'legendastv' is discarded
WARNING:subliminal.core:Provider 'legendastv' is discarded
WARNING:subliminal.core:Provider 'legendastv' is discarded
WARNING:subliminal.core:Provider 'legendastv' is discarded
WARNING:subliminal.core:Provider 'legendastv' is discarded
WARNING:subliminal.core:Provider 'legendastv' is discarded
WARNING:subliminal.core:Provider 'legendastv' is discarded
Downloading subtitles  [####################################]  100%                                           
Some providers have been discarded due to unexpected errors: legendastv
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider legendastv
INFO:subliminal.providers.legendastv:Logging out
DEBUG:subliminal.providers.legendastv:Logged out
0 subtitle downloaded for The.Walking.Dead.S07E01.HDTV.x264-KILLERS
```

**Comment by brenosabino** [comment]
same here

**Comment by Diaoul** [comment]
cc @ratoaq2
I think we need some way to detect unrar isn't installed and discard the provider earlier in that case.

**Comment by evertonbob** [comment]
After a "brew install unrar" everything is going fine, interesting that i've tried others "unrar" packages, but only this one did the trick.

**Comment by fernandog** [comment]
Fixed in develop.

**Comment by pannal** [comment]
This isn't really fixed.

It works for @brenosabino because he installed the older 5.3.0 beta 2 version of UnRAR. Using any of the latest UnRAR versions with rarfile doesn't work. 

`BadRarFile: Failed the read enough data` seems to be an implementation issue in `rarfile`.

**Comment by evertonbob** [comment]
> After a "brew install unrar" everything is going fine, interesting that i've tried others "unrar" packages, but only this one did the trick.
> EDIT: On Windows my solution was, install unrar with chocolatey package manager, no other solution or install method worked

i'd like to say, my install method of unRAR totally worked, one year and a half downloading any subtitles i tried from legendastv, not a single one gives me this error

**Comment by pannal** [comment]
@evertonbob can you get me the `unrar` binary you currently have on OSX? I don't have OSX myself, sadly.

**Comment by evertonbob** [comment]
> @evertonbob can you get me the unrar binary you currently have on OSX? I don't have OSX myself, sadly.
> 
> Edit: Also, can you tell me the version it returns when executed, both on OSX and Win32?
> Edit 2: The Win32 binary would be helpful as well.

Sorry for the waiting man, i was away from my computers.
Unrar at OSX 10.12 says 5.6.2 
 Windows 7 says it's Unrar 5.4.0,
uploaded both in this single zip, after testing with your given example "Magician_US_S03E12"

Hope it helps.

[2_unrar.zip](https://github.com/Diaoul/subliminal/files/1869717/2_unrar.zip)

**Comment by pannal** [comment]
@evertonbob thanks!

Although your binaries being able to extract the file doesn't mean anything. The issue lies in the implementation of the library `rarfile` after my initial analysis of the problem.

**Comment by pannal** [comment]
OK wow, I only now got why it didn't work before. It isn't an implementation issue of rarfile and certain unrar versions, at all: https://github.com/markokr/rarfile/issues/47
