### ISSUE TITLE
Some providers have been discarded due to unexpected errors

### ISSUE THREAD

**Issue by owenlejeune** [Diaoul/subliminal#831]
This is what is presented by --debug

Collecting videos  [####################################]  100%  /Volumes/STORAGE/Media/TV/American Dad/Season 13/S13E15 - Daesong Heavy Industries.mkvDEBUG:subliminal.cli:Collecting path /Volumes/STORAGE/Media/TV/American Dad/Season 13/S13E15 - Daesong Heavy Industries.mkv
INFO:subliminal.core:Scanning video 'S13E15 - Daesong Heavy Industries.mkv' in '/Volumes/STORAGE/Media/TV/American Dad/Season 13'
DEBUG:subliminal.core:Size is 209723305
DEBUG:subliminal.core:Computed hashes {'thesubdb': 'a8a4867d997c21950f95fc76caa3b652', 'opensubtitles': '4ca73d5cd2738213', 'shooter': 'b17f8ca7a4513e37ddb759d46c74f610;d55d5aa6d91d5743bae51dad6248ed10;b651bad90640cf4af5a6d31f3bfbb42c;29791137edbb36a21e07087533873f08', 'napiprojekt': '4ebc453c26c7a9421125d0ef081dddfd'}
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found audio_codec AAC
DEBUG:subliminal.refiners.metadata:Found embedded subtitle set([<Language [und]>])
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'American Dad'
DEBUG:subliminal.refiners.tvdb:Found 1 results
DEBUG:subliminal.refiners.tvdb:Found exact match on series u'American Dad'
DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'21935', u'rating': u'TV-14', u'overview': u"C.I.A. Agent Stan Smith is constantly fighting off terrorists who threaten the safety of the USA (sometimes causing more harm than good). His wife Francine is an average house wife with two kids, Hayley, Stan's only daughter, an average rebellious teenager and Steve, Stan's only son, a geek who enjoys Dungeons and Dragons, gaming and comic book conventions. Then there's Roger, the home's illegal (space) alien who the Smith's are keeping protected. Last but not least, there's Klaus, the Smith's wisecracking talking fish (swapped from  his human body years ago by the CIA).", u'firstAired': u'2005-02-06', u'id': 73141, u'aliases': [u'American Dad', u'American Dad !'], u'networkId': u'', u'network': u'TBS', u'zap2itId': u'EP00716445', u'seriesName': u'American Dad!', u'status': u'Continuing', u'added': u'', u'imdbId': u'tt0397306', u'lastUpdated': 1509952342, u'addedBy': None, u'genre': [u'Animation', u'Comedy'], u'banner': u'graphical/73141-g10.jpg', u'airsTime': u'10:00 PM', u'siteRatingCount': 310, u'airsDayOfWeek': u'Monday', u'runtime': u'25', u'siteRating': 8.5}
INFO:subliminal.refiners.tvdb:Getting series episode 13x15
DEBUG:subliminal.refiners.tvdb:Found episode {u'seriesId': 73141, u'airsAfterSeason': None, u'dvdEpisodeNumber': None, u'productionCode': u'AAJN15', u'overview': u"Stan loses his faith after Steve questions everything in the Bible, so Stan takes the family to Korea to investigate the rumors of a reinvented Noah's Ark.", u'airedSeasonID': 648358, u'thumbAdded': u'', u'episodeName': u'Daesong Heavy Industries', u'airedSeason': 13, u'airsBeforeSeason': None, u'showUrl': u'', u'id': 5546737, u'dvdDiscid': u'', u'filename': u'', u'dvdSeason': None, u'writers': [u'Greg Cohen'], u'airedEpisodeNumber': 15, u'absoluteNumber': None, u'thumbHeight': None, u'imdbId': u'tt4132644', u'lastUpdated': 1505885990, u'director': u'Chris Bennett', u'lastUpdatedBy': 112021, u'dvdChapter': None, u'airsBeforeEpisode': None, u'language': {u'overview': u'en', u'episodeName': u'en'}, u'thumbAuthor': 0, u'siteRatingCount': 5, u'directors': [u'Chris Bennett'], u'firstAired': u'2016-05-09', u'guestStars': [u'Michael Dorn'], u'siteRating': 5, u'thumbWidth': None}
INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:No need to search
Collecting videos  [####################################]  100%                                                                                        
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  S13E15 - Daesong Heavy Industries.mkvINFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages set([<Language [en]>])
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.core:Listing subtitles with provider 'shooter' and languages set([<Language [en]>])
INFO:subliminal.core:Initializing provider shooter
INFO:subliminal.core:Listing subtitles with provider 'podnapisi' and languages set([<Language [en]>])
INFO:subliminal.core:Initializing provider podnapisi
INFO:subliminal.providers.podnapisi:Searching subtitles {'sTE': 15, 'sXML': 1, 'sL': 'en', 'sY': 2005, 'sK': u'American Dad!', 'sTS': 13}
INFO:subliminal.core:Listing subtitles with provider 'tvsubtitles' and languages set([<Language [en]>])
INFO:subliminal.core:Initializing provider tvsubtitles
DEBUG:subliminal.providers.shooter:Searching subtitles {'lang': 'eng', 'pathinfo': '/Volumes/STORAGE/Media/TV/American Dad/Season 13/S13E15 - Daesong Heavy Industries.mkv', 'filehash': 'b17f8ca7a4513e37ddb759d46c74f610;d55d5aa6d91d5743bae51dad6248ed10;b651bad90640cf4af5a6d31f3bfbb42c;29791137edbb36a21e07087533873f08', 'format': 'json'}
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages set([<Language [en]>])
INFO:subliminal.core:Listing subtitles with provider 'addic7ed' and languages set([<Language [en]>])
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.core:Initializing provider addic7ed
ERROR:subliminal.providers.tvsubtitles:Episode 15 not found
INFO:subliminal.providers.opensubtitles:Logging in
INFO:subliminal.core:Skipping provider 'subscenter': no language to search for
INFO:subliminal.core:Listing subtitles with provider 'thesubdb' and languages set([<Language [en]>])
DEBUG:subliminal.providers.addic7ed:Getting show id with year
INFO:subliminal.core:Initializing provider thesubdb
DEBUG:subliminal.providers.addic7ed:Getting show id
INFO:subliminal.providers.thesubdb:Searching subtitles {'action': 'search', 'hash': 'a8a4867d997c21950f95fc76caa3b652'}
WARNING:subliminal.providers.addic7ed:Series not found in show ids
ERROR:subliminal.providers.addic7ed:No show id found for u'American Dad!' ({'country': None, 'year': 2005})
INFO:subliminal.providers.legendastv:Getting archives for title 40275 and language 2
DEBUG:subliminal.providers.thesubdb:No subtitles found
DEBUG:subliminal.providers.opensubtitles:Logged in with token 'efVyYSy-h4CemvOLhMzukUSrZT4'
INFO:subliminal.providers.opensubtitles:Searching subtitles [{'moviebytesize': '209723305', 'sublanguageid': u'eng', 'moviehash': '4ca73d5cd2738213'}, {'imdbid': u'4132644', 'sublanguageid': u'eng'}, {'sublanguageid': u'eng', 'tag': 'S13E15 - Daesong Heavy Industries.mkv'}, {'query': u'American Dad!', 'sublanguageid': u'eng', 'episode': 15, 'season': 13}]
DEBUG:subliminal.providers.opensubtitles:No subtitles found
DEBUG:subliminal.providers.podnapisi:No subtitles found
DEBUG:subliminal.providers.legendastv:Found 1 archives
INFO:subliminal.providers.legendastv:Releases not found in cache
INFO:subliminal.providers.legendastv:Downloading archive 56d66b870e72c
ERROR:subliminal.core:Unexpected error in provider 'legendastv'
Traceback (most recent call last):
  File "/usr/local/Cellar/subliminal/2.0.5/libexec/lib/python2.7/site-packages/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/local/Cellar/subliminal/2.0.5/libexec/lib/python2.7/site-packages/subliminal/providers/legendastv.py", line 440, in list_subtitles
    return [s for l in languages for s in self.query(l, title, season=season, episode=episode, year=video.year)]
  File "/usr/local/Cellar/subliminal/2.0.5/libexec/lib/python2.7/site-packages/subliminal/providers/legendastv.py", line 400, in query
    self.download_archive(a)
  File "/usr/local/Cellar/subliminal/2.0.5/libexec/lib/python2.7/site-packages/subliminal/providers/legendastv.py", line 336, in download_archive
    raise ValueError('Not a valid archive')
ValueError: Not a valid archive
INFO:subliminal.core:Discarding provider legendastv
DEBUG:subliminal.providers.shooter:No subtitles found
Downloading subtitles  [####################################]  100%                                       
Some providers have been discarded due to unexpected errors: legendastv
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider shooter
INFO:subliminal.core:Terminating provider legendastv
INFO:subliminal.core:Terminating provider tvsubtitles
INFO:subliminal.core:Terminating provider podnapisi
INFO:subliminal.core:Terminating provider addic7ed
INFO:subliminal.core:Terminating provider thesubdb
INFO:subliminal.core:Terminating provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging out
DEBUG:subliminal.providers.opensubtitles:Logged out
Downloaded 0 subtitle

**Comment by marcelpaulo** [comment]
@owenlejeune, I wouldn't be able to explain to you why, but perhaps running this might fix it:

`subliminal cache --clear-subliminal`

I think I ran into the same problem after I upgraded subliminal, and that's how I fixed it. Perhaps someone from the team might correct or explain.

**Comment by owenlejeune** [comment]
@marcelpaulo Thanks for the suggestion.  Unfortunately, that didn't fix my problem.  Appears to be a problem with some of the providers "Some providers have been discarded due to unexpected errors: opensubtitles, legendastv, addic7ed"

**Comment by yarez0** [comment]
Hi, seems that there is a problem with show IDs, I got this problem with Mr Robot, The Flash and some other shows.

root@syno:~# subliminal --debug --addic7ed xxxxx yyyyy download -f -vv -l fr -s /volume1/video/Series/Mr._Robot/Season_3/Mr.Robot.S03E06.eps3.5_kill-process.inc.WEBDL-1080p.NTb.mkv
Collecting videos  [####################################]  100%  /volume1/video/Series/Mr._Robot/Season_3/Mr.Robot.S03E06.eps3.5_kill-process.inc.WEBDL-1080p.NTb.mkvDEBUG:subliminal.cli:Collecting path /volume1/video/Series/Mr._Robot/Season_3/Mr.Robot.S03E06.eps3.5_kill-process.inc.WEBDL-1080p.NTb.mkv
INFO:subliminal.core:Scanning video 'Mr.Robot.S03E06.eps3.5_kill-process.inc.WEBDL-1080p.NTb.mkv' in '/volume1/video/Series/Mr._Robot/Season_3'
DEBUG:subliminal.core:Size is 2000673858
DEBUG:subliminal.core:Computed hashes {'thesubdb': '18c2e14d3c30371e975d9643c507963b', 'opensubtitles': '8c470aab4b058656', 'shooter': 'cc75cf638c7c924c8e878a8f1ba93a52;cb710bde499aff2f09c236c2fb64ff63;baaba2409989b026b7e91dc37c70aa9c;4c34012b3515993649242a0d1abcebd2', 'napiprojekt': 'c45aced25846d8858bbaa5e882b61541'}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found resolution 1080p
DEBUG:subliminal.refiners.metadata:Found video_codec h264
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'Mr Robot'
DEBUG:subliminal.refiners.tvdb:Found 1 results
DEBUG:subliminal.refiners.tvdb:Found exact match on series u'Mr. Robot'
DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'195881', u'rating': u'TV-MA', u'overview': u'Mr. Robot follows Elliot, a young programmer who works as a cyber-security engineer by day and a vigilante hacker by night. Elliot finds himself at a crossroads when the mysterious leader of an underground hacker group recruits him to destroy the corporation he is paid to protect.', u'firstAired': u'2015-06-24', u'zap2itId': u'EP02164264', u'aliases': [], u'networkId': u'', u'network': u'USA Network', u'id': 289590, u'seriesName': u'Mr. Robot', u'status': u'Continuing', u'added': u'2014-12-19 14:45:45', u'imdbId': u'tt4158110', u'lastUpdated': 1511815084, u'addedBy': 79791, u'genre': [u'Crime', u'Drama', u'Thriller'], u'banner': u'graphical/289590-g8.jpg', u'airsTime': u'10:00 PM', u'siteRatingCount': 162, u'airsDayOfWeek': u'Wednesday', u'runtime': u'50', u'siteRating': 9}
INFO:subliminal.refiners.tvdb:Getting series episode 3x6
DEBUG:subliminal.refiners.tvdb:Found episode {u'seriesId': 289590, u'airsAfterSeason': None, u'dvdEpisodeNumber': None, u'productionCode': u'', u'overview': u'Elliot faces off with Mr. Robot; Dom gets tired of the red tape; Tyrell has a new plan.', u'airedSeasonID': 703652, u'thumbAdded': u'2017-11-15 21:02:28', u'episodeName': u'eps3.5_kill-process.inc', u'airedSeason': 3, u'airsBeforeSeason': None, u'showUrl': u'', u'id': 6141716, u'dvdDiscid': u'', u'filename': u'episodes/289590/6141716.jpg', u'dvdSeason': None, u'writers': [u'Kyle Bradstreet'], u'airedEpisodeNumber': 6, u'absoluteNumber': 28, u'thumbHeight': u'225', u'imdbId': u'tt6635194', u'lastUpdated': 1511542261, u'director': u'Sam Esmail', u'lastUpdatedBy': 427771, u'dvdChapter': None, u'airsBeforeEpisode': None, u'language': {u'overview': u'en', u'episodeName': u'en'}, u'thumbAuthor': 438962, u'siteRatingCount': 3, u'directors': [u'Sam Esmail'], u'firstAired': u'2017-11-15', u'guestStars': [], u'siteRating': 9, u'thumbWidth': u'400'}
INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:No need to search
Collecting videos  [####################################]  100%                                                                                      
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  Mr.Robot.S03E06.eps3.5_kill-process.inc.WEBDL-1080p.NTb.mkvINFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages set([<Language [fr]>])
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.core:Skipping provider 'shooter': no language to search for
INFO:subliminal.core:Listing subtitles with provider 'podnapisi' and languages set([<Language [fr]>])
INFO:subliminal.core:Listing subtitles with provider 'tvsubtitles' and languages set([<Language [fr]>])
INFO:subliminal.core:Initializing provider podnapisi
INFO:subliminal.core:Initializing provider tvsubtitles
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages set([<Language [fr]>])
INFO:subliminal.core:Listing subtitles with provider 'addic7ed' and languages set([<Language [fr]>])
INFO:subliminal.providers.podnapisi:Searching subtitles {'sTE': 6, 'sXML': 1, 'sL': 'fr', 'sY': 2015, 'sK': u'Mr. Robot', 'sTS': 3}
INFO:subliminal.core:Skipping provider 'subscenter': no language to search for
INFO:subliminal.core:Listing subtitles with provider 'thesubdb' and languages set([<Language [fr]>])
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.core:Initializing provider addic7ed
INFO:subliminal.core:Initializing provider thesubdb
INFO:subliminal.providers.opensubtitles:Logging in
INFO:subliminal.providers.legendastv:Searching title u'mr robot'
INFO:subliminal.providers.addic7ed:Logging in
INFO:subliminal.providers.thesubdb:Searching subtitles {'action': 'search', 'hash': '18c2e14d3c30371e975d9643c507963b'}
DEBUG:subliminal.providers.addic7ed:Logged in
DEBUG:subliminal.providers.legendastv:Found 3 titles
DEBUG:subliminal.providers.thesubdb:Found subtitle <TheSubDBSubtitle '18c2e14d3c30371e975d9643c507963b-pt-BR' [pt-BR]>
INFO:subliminal.providers.tvsubtitles:Searching show id for u'Mr. Robot'
DEBUG:subliminal.providers.podnapisi:Found subtitle <PodnapisiSubtitle '0v9E' [fr]>
DEBUG:subliminal.providers.tvsubtitles:Found show id 1773
INFO:subliminal.providers.addic7ed:Getting show ids
ERROR:subliminal.core:Unexpected error in provider 'opensubtitles'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/lib/python2.7/site-packages/subliminal/core.py", line 68, in __getitem__
    provider.initialize()
  File "/usr/lib/python2.7/site-packages/subliminal/providers/opensubtitles.py", line 138, in initialize
    'subliminal v%s' % __short_version__))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1313, in single_request
    response = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1183, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 457, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 413, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)
encoding error : input conversion failed due to input error, bytes 0x8D 0x20 0x6E 0x6F
encoding error : input conversion failed due to input error, bytes 0x8D 0x20 0x6E 0x6F
encoding error : input conversion failed due to input error, bytes 0x8D 0x20 0x6E 0x6F
DEBUG:subliminal.providers.addic7ed:Found 507 show ids
DEBUG:subliminal.providers.addic7ed:Getting show id with year
DEBUG:subliminal.providers.addic7ed:Getting show id
WARNING:subliminal.providers.addic7ed:Series not found in show ids
INFO:subliminal.providers.legendastv:Searching title u'mr. robot'
DEBUG:subliminal.providers.legendastv:Found 3 titles
INFO:subliminal.providers.addic7ed:Searching show ids with {'search': u'Mr. Robot', 'Submit': 'Search'}
ERROR:subliminal.core:Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/lib/python2.7/site-packages/subliminal/providers/addic7ed.py", line 273, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "/usr/lib/python2.7/site-packages/subliminal/providers/addic7ed.py", line 228, in query
    show_id = self.get_show_id(series, year, country)
  File "/usr/lib/python2.7/site-packages/subliminal/providers/addic7ed.py", line 222, in get_show_id
    show_id = self._search_show_id(series)
  File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 1231, in decorate
    should_cache_fn)
  File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 833, in get_or_create
    async_creator) as value:
  File "/usr/lib/python2.7/site-packages/dogpile/lock.py", line 154, in __enter__
    return self._enter()
  File "/usr/lib/python2.7/site-packages/dogpile/lock.py", line 94, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/lib/python2.7/site-packages/dogpile/lock.py", line 145, in _enter_create
    created = self.creator()
  File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 800, in gen_value
    created_value = creator()
  File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 1227, in creator
    return fn(*arg, **kw)
  File "/usr/lib/python2.7/site-packages/subliminal/providers/addic7ed.py", line 170, in _search_show_id
    raise TooManyRequests()
TooManyRequests
INFO:subliminal.providers.tvsubtitles:Getting the page of show id 1773, season 3
DEBUG:subliminal.providers.tvsubtitles:Found episode ids {1: 67953, 2: 67992, 3: 67993, 4: 67994, 5: 67995, 6: 67996, 7: 67997, 8: 67998, 9: 67999, 10: 68000}
INFO:subliminal.providers.tvsubtitles:Getting the page for episode 67996
INFO:subliminal.providers.legendastv:Getting archives for title 45771 and language 4
DEBUG:subliminal.providers.legendastv:Found 0 archives
DEBUG:subliminal.providers.tvsubtitles:Found subtitle <TVsubtitlesSubtitle '332103' [en]>
DEBUG:subliminal.providers.tvsubtitles:Found subtitle <TVsubtitlesSubtitle '332154' [fr]>
INFO:subliminal.core:Discarding provider opensubtitles
INFO:subliminal.core:Discarding provider addic7ed
INFO:subliminal.score:Computing score of <PodnapisiSubtitle '0v9E' [fr]> for video <Episode [u'Mr. Robot', 2015, 3x6]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 359, 'format': 7, 'series': 180, 'audio_codec': 3, 'year': 90, 'hearing_impaired': 1, 'episode': 30, 'season': 30, 'video_codec': 2, 'resolution': 2, 'release_group': 15}
DEBUG:subliminal.score:Found matches set(['episode', 'video_codec', 'season', 'series', 'year'])
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 333 with final matches set(['episode', 'video_codec', 'season', 'series', 'year', 'hearing_impaired'])
INFO:subliminal.score:Computing score of <TVsubtitlesSubtitle '332154' [fr]> for video <Episode [u'Mr. Robot', 2015, 3x6]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 359, 'format': 7, 'series': 180, 'audio_codec': 3, 'year': 90, 'hearing_impaired': 1, 'episode': 30, 'season': 30, 'video_codec': 2, 'resolution': 2, 'release_group': 15}
DEBUG:subliminal.score:Found matches set(['series', 'year', 'episode', 'season'])
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 331 with final matches set(['series', 'year', 'episode', 'hearing_impaired', 'season'])
INFO:subliminal.core:Downloading subtitle <PodnapisiSubtitle '0v9E' [fr]>
INFO:subliminal.providers.podnapisi:Downloading subtitle <PodnapisiSubtitle '0v9E' [fr]>
INFO:subliminal.subtitle:Guessing encoding for language fr
DEBUG:subliminal.subtitle:Trying encodings ['utf-8', 'latin-1']
INFO:subliminal.subtitle:Guessed encoding utf-8
INFO:subliminal.subtitle:Guessing encoding for language fr
DEBUG:subliminal.subtitle:Trying encodings ['utf-8', 'latin-1']
INFO:subliminal.subtitle:Guessed encoding utf-8
DEBUG:subliminal.core:All languages downloaded
Downloading subtitles  [####################################]  100%
Some providers have been discarded due to unexpected errors: opensubtitles, addic7ed
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider thesubdb
INFO:subliminal.core:Terminating provider podnapisi
INFO:subliminal.core:Terminating provider legendastv
INFO:subliminal.core:Terminating provider tvsubtitles
INFO:subliminal.core:Terminating provider addic7ed
INFO:subliminal.providers.addic7ed:Logging out
DEBUG:subliminal.providers.addic7ed:Logged out
INFO:subliminal.core:Saving <PodnapisiSubtitle '0v9E' [fr]> to '/volume1/video/Series/Mr._Robot/Season_3/Mr.Robot.S03E06.eps3.5_kill-process.inc.WEBDL-1080p.NTb.srt'
1 subtitle downloaded for Mr.Robot.S03E06.eps3.5_kill-process.inc.WEBDL-1080p.NTb.mkv
INFO:subliminal.score:Computing score of <PodnapisiSubtitle '0v9E' [fr]> for video <Episode [u'Mr. Robot', 2015, 3x6]> with {'hearing_impaired': None}
DEBUG:subliminal.score:Using scores {'hash': 359, 'format': 7, 'series': 180, 'audio_codec': 3, 'year': 90, 'hearing_impaired': 1, 'episode': 30, 'season': 30, 'video_codec': 2, 'resolution': 2, 'release_group': 15}
DEBUG:subliminal.score:Found matches set(['episode', 'video_codec', 'season', 'series', 'year'])
INFO:subliminal.score:Computed score 332 with final matches set(['episode', 'video_codec', 'season', 'series', 'year'])
  - [ 92.2] French subtitle from podnapisi (match on series, year, episode, season, video_codec)
root@syno:~#

**Comment by fernandog** [comment]
@Diaoul should we catch this one as ServiceUnavailable?


File "/usr/lib/python2.7/httplib.py", line 413, in _read_status
line = self.fp.readline(_MAXLINE + 1)
File "/usr/lib/python2.7/socket.py", line 480, in readline
data = self._sock.recv(self._rbufsize)
File "/usr/lib/python2.7/ssl.py", line 756, in recv
return self.read(buflen)
File "/usr/lib/python2.7/ssl.py", line 643, in read
v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)

**Comment by Diaoul** [comment]
Only if we can narrow it down to a time out. Raise the rest.

**Comment by fernandog** [comment]
@owenlejeune Both errors are fixed in develop version

**Comment by ComputingFroggy** [comment]
I am running version 2.1.0 on Ubuntu 20.04, and I still have this bug ! ! :-(
