### ISSUE TITLE
TypeError: decode() argument 1 must be string, not None

### ISSUE THREAD

**Issue by JingenChen** [Diaoul/subliminal#942]
Traceback (most recent call last):
  File "get_sub.py", line 13, in <module>
    subtitles = download_best_subtitles(videos, {Language('zho'), Language('eng')})
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 647, in download_best_subtitles
    compute_score=compute_score)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 227, in download_best_subtitles
    if self.download_subtitle(subtitle):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 182, in download_subtitle
    if not subtitle.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/subliminal/subtitle.py", line 85, in is_valid
    if not self.text:
  File "/usr/local/lib/python2.7/dist-packages/subliminal/subtitle.py", line 76, in text
    return self.content.decode(self.guess_encoding(), errors='replace')
TypeError: decode() argument 1 must be string, not None

**Comment by ratoaq2** [comment]
Can you try with latest develop branch and check if this is still an issue?

**Comment by ratoaq2** [comment]
Fixed by 78d8f26fdd5c136d264033859ff92c1b86ee8727

**Comment by MatthK** [comment]
I still have this error in Medusa.

https://github.com/pymedusa/Medusa/issues/7072

**Comment by ratoaq2** [comment]
It seems medusa is not up to date
